---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - gnupg-agent
      - software-properties-common

- name: Give specific rights
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings


- name: Setup the Docker repository GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Give specific rights
  ansible.builtin.shell: |
    chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  ansible.builtin.shell: |
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    filename: docker

- name: Install Docker Engine
  apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin
  notify:
  - restart docker

- name: Test by running a docker container
  ansible.builtin.shell: |
    docker run hello-world

  handlers:
      - name: restart docker
        service:
          name: docker
          state: restarted


- name: Verify Docker Compose version
  ansible.builtin.command:
    cmd: "docker compose version"
  register: compose_version
  changed_when: false

- name: Print Docker Compose version
  ansible.builtin.debug:
    msg: "{{ compose_version.stdout }}"
    