apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      nfs:
        server: my.nfs.server.local
        path: "/exports"
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:  # Minimal resources given
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      livenessProbe:  # When ready to run
        httpGet:
          path: /healthy  # The url of the page that is tested; it can be /home
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 20 # Every 20 seconds, there is a request that tests if the container is OK
        failureThreshold: 3 # If 3 times a request fails, the container is restarted
      readinessProbe: # When ready to accept request
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
        successThreshold: 1
