---
# tasks file for roles/gitlab

- name: Install Gitlab and his dependencies
  hosts: all
  become: yes
  tasks: 
  - name: Update apt cache
    update_cache: yes

- name: Install GitLab dependencies  
  ansible.builtin.apt: 
    name:
    - update
    - wget 
    - ca-certificates 
    - curl 
    - apt-transport-https 
    - gnupg2 
  state: present

- name: Install Gitlab repository on debian
  ansible.builtin.apt: |
    curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

- name: Install Gitlab
  ansible.builtin.apt:
    name: 
      - gitlab-ce
  state: present


- name: Configure Gitlab
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: "external_url 'http://crazytechgeek.info'"
    backrefs: yes

- name: Set LetsEncrypt contact emails
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^letsencrypt\\[\'contact_emails\'\\]'
    line: "letsencrypt['contact_emails'] = ['admin@linuxtechi.com']"
    backrefs: yes

- name: Reconfigure GitLab
  ansible.builtin.shell:
    cmd: gitlab-ctl reconfigure